[package]
name = "rust-admin"
version = "0.1.0"
authors = ["john.zhao <john.zhao@newType.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
juniper = "0.14"
structopt = "0.3"
